"""research_sources 新增 content 列

Revision ID: 39b5ffae3624
Revises: c02701951a41
Create Date: 2026-06-25 17:32:40.052944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b5ffae3624'
down_revision: Union[str, Sequence[str], None] = 'c02701951a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sources', sa.Column('content', sa.Text(), server_default=sa.text('NULL'), nullable=True, comment="网页 Markdown 正文；fetch_status='success' 时写入"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sources', 'content')
    # ### end Alembic commands ###
