"""init

Revision ID: 7685a032ccd7
Revises: 
Create Date: 2026-06-20 17:33:34.769404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7685a032ccd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='bcrypt 哈希'),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), server_default=sa.text("'active'"), nullable=False, comment='disabled 后拒绝登录与 Token 刷新'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False, comment='refresh_token 的 SHA-256 哈希，不存明文'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间（创建后 7 天）'),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True, comment='吊销时间（NULL=有效，非NULL=已吊销）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_user_active', 'refresh_tokens', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index('idx_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False, comment='用户输入的研究主题'),
    sa.Column('requirements', sa.JSON(), nullable=False, comment='研究要求（task_type, depth, max_sources, language...）'),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'partially_completed', 'failed', 'canceled', 'paused', name='task_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('current_phase', sa.Enum('planning', 'searching', 'fetching', 'reranking', 'synthesizing', 'building_evidence_graph', 'rendering', name='task_phase'), server_default=sa.text('NULL'), nullable=True),
    sa.Column('execution_context', sa.JSON(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('total_steps', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_steps', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_sources', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_evidence', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_code', sa.String(length=50), server_default=sa.text('NULL'), nullable=True),
    sa.Column('error_message', sa.Text(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('recoverable', sa.Boolean(), server_default=sa.text('NULL'), nullable=True, comment='是否可以断点续跑（NULL = 未失败）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True, comment='Worker 拾取时间'),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created', 'research_tasks', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_status', 'research_tasks', ['status'], unique=False)
    op.create_index('idx_user', 'research_tasks', ['user_id'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('parent_section_id', sa.Integer(), server_default=sa.text('NULL'), nullable=True, comment='父章节（支持嵌套）'),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False, comment='Markdown 正文'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['parent_section_id'], ['report_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent', 'report_sections', ['parent_section_id'], unique=False)
    op.create_index('idx_task', 'report_sections', ['task_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='报告中的引用编号 [1], [2]...'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), server_default=sa.text('NULL'), nullable=True),
    sa.Column('domain', sa.String(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('fetch_status', sa.Enum('success', 'timeout', 'blocked', 'empty', name='fetch_status'), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task', 'research_sources', ['task_id'], unique=False)
    op.create_index('uk_task_url', 'research_sources', ['task_id', 'url'], unique=True, mysql_length={'url': 255})
    op.create_table('research_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('step_type', sa.Enum('planning', 'search', 'fetch', 'rerank', 'synthesis', 'evidence_graph', 'render', name='step_type'), nullable=False),
    sa.Column('parent_step_id', sa.String(length=36), server_default=sa.text('NULL'), nullable=True, comment='DAG 边：父步骤'),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', 'retrying', name='step_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('label', sa.String(length=200), server_default=sa.text('NULL'), nullable=True, comment='如 "搜索子问题 2：NIST PQC 标准进展"'),
    sa.Column('input', sa.JSON(), server_default=sa.text('NULL'), nullable=True, comment='Step 输入参数'),
    sa.Column('output', sa.JSON(), server_default=sa.text('NULL'), nullable=True, comment='Step 产出'),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='0 = 使用阶段默认值'),
    sa.Column('error_code', sa.String(length=50), server_default=sa.text('NULL'), nullable=True),
    sa.Column('error_message', sa.Text(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), server_default=sa.text('NULL'), nullable=True, comment='执行耗时（毫秒）'),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['parent_step_id'], ['research_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent', 'research_steps', ['parent_step_id'], unique=False)
    op.create_index('idx_task', 'research_steps', ['task_id'], unique=False)
    op.create_index('idx_task_status', 'research_steps', ['task_id', 'status'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=36), server_default=sa.text('NULL'), nullable=True, comment='产生此证据的 Step（NULL = 非 Step 产生）'),
    sa.Column('content', sa.Text(), nullable=False, comment='证据原文片段'),
    sa.Column('relevance_score', sa.DECIMAL(precision=4, scale=3), server_default=sa.text('NULL'), nullable=True, comment='Rerank 相关性分数 (0.000-1.000)'),
    sa.Column('used_in_sections', sa.JSON(), server_default=sa.text('NULL'), nullable=True, comment='如 ["1", "2.1"]'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['research_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score', 'evidence_items', ['task_id', sa.text('relevance_score DESC')], unique=False)
    op.create_index('idx_source', 'evidence_items', ['source_id'], unique=False)
    op.create_index('idx_task', 'evidence_items', ['task_id'], unique=False)
    op.create_table('section_evidence',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['report_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_evidence')
    op.drop_index('idx_task', table_name='evidence_items')
    op.drop_index('idx_source', table_name='evidence_items')
    op.drop_index('idx_score', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('idx_task_status', table_name='research_steps')
    op.drop_index('idx_task', table_name='research_steps')
    op.drop_index('idx_parent', table_name='research_steps')
    op.drop_table('research_steps')
    op.drop_index('idx_task', table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index('idx_task', table_name='report_sections')
    op.drop_index('idx_parent', table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index('idx_user', table_name='research_tasks')
    op.drop_index('idx_status', table_name='research_tasks')
    op.drop_index('idx_created', table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index('idx_user_id', table_name='refresh_tokens')
    op.drop_index('idx_user_active', table_name='refresh_tokens')
    op.drop_index('idx_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
