"""research_sources content 列改为 MEDIUMTEXT

Revision ID: f277d4d29190
Revises: 39b5ffae3624
Create Date: 2026-06-25 23:15:25.197818

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f277d4d29190'
down_revision: Union[str, Sequence[str], None] = '39b5ffae3624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_sources', 'content',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_comment="网页 Markdown 正文；fetch_status='success' 时写入",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_sources', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_comment="网页 Markdown 正文；fetch_status='success' 时写入",
               existing_nullable=True)
    # ### end Alembic commands ###
