"""traces表新增evidence_review JSON列

Revision ID: 3bc9273cea34
Revises: e4f5a6b7c8d9
Create Date: 2026-06-16 00:39:48.810117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bc9273cea34'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               comment='外部暴露标识符（UUID），API/URL 使用',
               existing_nullable=False,
               existing_server_default=sa.text('(uuid())'))
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='会话元数据更新时间（标题/归档/pin 等）',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               comment='外部暴露标识符（UUID），API/URL 使用',
               existing_nullable=False,
               existing_server_default=sa.text('(uuid())'))
    op.alter_column('knowledge_bases', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               comment='外部暴露标识符（UUID），API/URL 使用',
               existing_comment='外部暴露标识符（UUID v4），API/URL 使用')
    op.create_unique_constraint(None, 'knowledge_bases', ['uuid'])
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='过期时间（创建后 7 天，UTC）',
               existing_comment='过期时间（创建后 7 天）',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=mysql.DATETIME(),
               comment='吊销时间（NULL=有效，非NULL=已吊销，UTC）',
               existing_comment='吊销时间（NULL=有效，非NULL=已吊销）',
               existing_nullable=True)
    op.add_column('traces', sa.Column('evidence_review', sa.JSON(), nullable=True, comment='证据审查阶段详情（chunk 分类 + REJECT 决策 + post-LLM 审计结果）'))
    op.alter_column('traces', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间（UTC）',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('active', 'disabled'),
               comment=None,
               existing_comment='active（正常）/ disabled（禁用）',
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('active', 'disabled'),
               comment='active（正常）/ disabled（禁用）',
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
    op.alter_column('traces', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间（UTC）',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('traces', 'evidence_review')
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=mysql.DATETIME(),
               comment='吊销时间（NULL=有效，非NULL=已吊销）',
               existing_comment='吊销时间（NULL=有效，非NULL=已吊销，UTC）',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='过期时间（创建后 7 天）',
               existing_comment='过期时间（创建后 7 天，UTC）',
               existing_nullable=False)
    op.drop_constraint(None, 'knowledge_bases', type_='unique')
    op.alter_column('knowledge_bases', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               comment='外部暴露标识符（UUID v4），API/URL 使用',
               existing_comment='外部暴露标识符（UUID），API/URL 使用')
    op.alter_column('documents', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='外部暴露标识符（UUID），API/URL 使用',
               existing_nullable=False,
               existing_server_default=sa.text('(uuid())'))
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='会话元数据更新时间（标题/归档/pin 等）',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='外部暴露标识符（UUID），API/URL 使用',
               existing_nullable=False,
               existing_server_default=sa.text('(uuid())'))
    # ### end Alembic commands ###
