"""research_steps 新增 cost 列

Revision ID: fd49212435a6
Revises: f277d4d29190
Create Date: 2026-06-26 13:30:19.197653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd49212435a6'
down_revision: Union[str, Sequence[str], None] = 'f277d4d29190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_steps', sa.Column('cost', sa.JSON(), server_default=sa.text('NULL'), nullable=True, comment='Step 级成本：{input_tokens, output_tokens, estimated_cost_usd, model}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_steps', 'cost')
    # ### end Alembic commands ###
