"""添加idx_user_name唯一索引

Revision ID: 687b64790b37
Revises: 04b3e0425da8
Create Date: 2026-05-16 19:04:53.827574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687b64790b37'
down_revision: Union[str, Sequence[str], None] = '04b3e0425da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_user_name', 'knowledge_bases', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_user_name', 'knowledge_bases', type_='unique')
    # ### end Alembic commands ###
