"""Phase 4.2: refresh_tokens 表

Revision ID: d2ed146c7d8e
Revises: 9a1b2c3d4e5f
Create Date: 2026-06-06 15:32:51.004106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ed146c7d8e'
down_revision: Union[str, Sequence[str], None] = '9a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False, comment='refresh_token 的 SHA-256 哈希，不存明文'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间（创建后 7 天）'),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True, comment='吊销时间（NULL=有效，非NULL=已吊销）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_user_active', 'refresh_tokens', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index('idx_user_id', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='refresh_tokens')
    op.drop_index('idx_user_active', table_name='refresh_tokens')
    op.drop_index('idx_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
